-- CREATE DATABASE sullivan_backend_test;


CREATE TABLE IF NOT EXISTS public.users (
    -- id will be a ULID generated by app
    id char(26) NOT NULL,
    username varchar(255) NOT NULL,
    email varchar(320) NOT NULL,
    password varchar(255) NOT NULL,
    CONSTRAINT pk_user_id PRIMARY KEY (id),
    CONSTRAINT ux_user_username UNIQUE (username),
    CONSTRAINT ux_user_email UNIQUE (email)
);

